"""empty message

Revision ID: 674670c419e7
Revises: da5073734ff5
Create Date: 2023-03-31 10:38:07.886910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674670c419e7'
down_revision = 'da5073734ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cells_cause',
    sa.Column('cell', sa.Integer(), nullable=False),
    sa.Column('cause', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cell')
    )
    op.drop_table('cells')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cells',
    sa.Column('cell', sa.INTEGER(), nullable=False),
    sa.Column('cause', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('cell')
    )
    op.drop_table('cells_cause')
    # ### end Alembic commands ###
