"""empty message

Revision ID: ab049cf93d13
Revises: 674670c419e7
Create Date: 2023-03-31 10:46:33.262072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab049cf93d13'
down_revision = '674670c419e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cells_cause', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cells_cause', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
